import sys 
import requests # import the requests library
from bs4 import BeautifulSoup # import beautifulsoup

if len(sys.argv) !=2:
   print("This program requires one argument; url of your choice")
   exit()

url_link = sys.argv[1]

website_response = requests.get(url_link) 

# print(website_response.text[:500])

website_soup_html = BeautifulSoup(website_response.text, "html.parser")

website_soup_text = website_soup_html.get_text()

website_data = open('website.txt', 'w')
website_data.write(website_soup_text)
website_data.close()

def getTitles(soupdata):  
  titles = soupdata.select("p") # Changed h2 to p element
  if titles:
    for t in titles:
      print(t.text)
      
# print("AFR........")
# getTitles(africa_soup_html)

########

f = open('website.txt', 'r') # Opened text file for reading
website = f.read() # Assigned variable to text file

webdic = {} # Created an empty dictionary

for line in website.splitlines(): # Loop through each line in text file
    for word in line.split(): # Loop through each word in each line by splitting a string into a list 
        # print(word)
        uppercase_word = word.upper() # Make all words uppercase to avoid case sensitivity 
        if uppercase_word in webdic:
            webdic[uppercase_word] = webdic[uppercase_word] + 1
        else: 
            webdic[uppercase_word] = 1

sorted_keys = sorted(webdic, key=webdic.get)
sorted_keys.reverse()
# print(sorted_keys)

skip = [
    # Special characters
    '.', ',', '!', '?', '"', "'", ':', ';', 
    '(', ')', '[', ']', '{', '}', '<', '>', 
    '@', '#', '$', '%', '^', '&', '*', '-', '_', '–', '+', '=',
    '/', '\\', '|', '~', '`',
    '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
    '\n', '\t', '\r',
    
    # Stop words
    'A', 'AN', 'THE',
    'I', 'ME', 'MY', 'MINE', 'MYSELF',
    'YOU', 'YOUR', 'YOURS', 'YOURSELF',
    'HE', 'HIM', 'HIS', 'HIMSELF',
    'SHE', 'HER', 'HERS', 'HERSELF',
    'IT', 'ITS', 'ITSELF',
    'WE', 'US', 'OUR', 'OURS', 'OURSELVES',
    'THEY', 'THEM', 'THEIR', 'THEIRS', 'THEMSELVES',
    'THIS', 'THAT', 'THESE', 'THOSE',
    'WHO', 'WHOM', 'WHOSE',
    'WHAT', 'WHICH',
    'IN', 'ON', 'AT', 'TO', 'FOR', 'WITH', 'BY', 'FROM',
    'UP', 'DOWN', 'OVER', 'UNDER', 'AGAIN', 'AGAINST',
    'OF', 'OFF', 'OUT', 'INTO', 'DURING', 'BEFORE', 'AFTER',
    'ABOVE', 'BELOW', 'BETWEEN', 'THROUGH', 'THROUGHOUT',
    'AND', 'BUT', 'OR', 'NOR', 'SO', 'YET',
    'BECAUSE', 'ALTHOUGH', 'UNLESS', 'SINCE',
    'AM', 'IS', 'ARE', 'WAS', 'WERE', 'BE', 'BEEN', 'BEING',
    'HAVE', 'HAS', 'HAD', 'HAVING',
    'DO', 'DOES', 'DID', 'DOING',
    'WILL', 'WOULD', 'SHALL', 'SHOULD', 'MAY', 'MIGHT',
    'MUST', 'CAN', 'COULD',
    'NOT', 'VERY', 'HERE', 'THERE', 'NOW', 'THEN',
    'JUST', 'ONLY', 'MORE', 'MOST', 'ALSO', 'ELSE',
    'TOO', 'WELL', 'HOWEVER', 'WHEN', 'WHERE', 'WHY',
    'HOW', 'ALL', 'ANY', 'BOTH', 'EACH', 'FEW', 'MANY',
    'SOME', 'SUCH',
    'ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', 'SIX', 'SEVEN',
    'EIGHT', 'NINE', 'TEN', 'FIRST', 'SECOND', 'THIRD',
    'ABOUT', 'IF', 'AS', 'THAN', 'WHILE', 'YES', 'NO',
    'OTHER', 'NEW', 'OLD', 'GOOD', 'HIGH', 'LOW'
] # List of common words and chracters generated by AI

filtered_words = []

for word in sorted_keys: 
   if word in skip:
      continue
   else: 
      filtered_words.append(word)

print(filtered_words[0:9]) # Slice list to top 10 most frequent words
# Africa Archive Ans: ['HIMMELHEBER', 'LIBERIA,', 'HANS', 'ART', 'INFORMATION', 'MASK', 'CÔTE', 'ODER', 'OBERHOFER'] 
# Blog Ans: ['DATA', 'SOCIAL', 'BIG', 'PINGBACK:', 'CATEGORIES', 'INFORMATION', '19TH', 'KNOWLEDGE', 'PROBLEMS']

# Project applicaiton idea: To aid the research for my thesis project about budiling a web archive for Ethiopian art, I'm interested in using this kind of code to see whether writings about Ethiopian art mainly center around the traditional religious art rather than other styles. I could maybe scrape data from different online books, articles, archives etc about this topic and see if the most frequent words are related to religion. I can compare it to searches on more widely acknowleged art such as European art and see the difference in results. 