numerical = ("New media object can be described with mathmatical function.", "A new media object is subject to algorithmic manipulation.", "Converting continuous data into a numerical representation is called digitization.")
modularity = ("Media elements are represented as collections of discrete samples.", "These elements maintain their seperate identities without losing their independence.")
automation = ("Numerical coding and modular structure allows human intentionality to be removed from creative process.", "For example, photoshop and artificial intelligence.")
variability = ("Something not fixed but can exist in infinite versions.")
transcoding = ("Consequence of computerization or turning media into computer data.")
